
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fast-api
  namespace: default
  labels:
    app: fast-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api
    spec:
      containers:
        - name: fast-api
          image: docker.pkg.github.com/caiovbraga/bpdts-demo/fast-api:v1.0-build_2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8000
            protocol: TCP
      imagePullSecrets:
        - name: github-credentials2      
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: fast-api
  ports:
  - name: fast-api
    port: 8000
    protocol: TCP
    targetPort: 8000